# Generated by Django 4.2.7 on 2023-11-06 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acaunt', '0002_remove_profile_user_remove_profile_userimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='profile',
        ),
    ]
