# Generated by Django 4.2.7 on 2023-11-09 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='post',
            name='vie_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
