# Generated by Django 4.2.7 on 2023-11-18 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_post_dislikes_count_post_likes_count_like_dislike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Description',
            field=models.CharField(max_length=40000),
        ),
    ]
